eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

paymentendpoint: http://PAYMENT-SERVICE/foodPayment/makePayment

microservices:
  payment-service:
    endpoints:
      uri: http://PAYMENT-SERVICE/foodPayment/makePayment
  order-service:
    endpoints:
      uri: http://ORDER-SERVICE/foodOrder/order
